import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  apiSidebar: [{ type: "autogenerated", dirName: "api" }],
  productSidebar: [{ type: "autogenerated", dirName: "product" }],
};

export default sidebars;
